### ISSUE TITLE
Honeyframe work Ver 3.1.1

### ISSUE THREAD

**Issue by drazenbencevic** [bitfinexcom/bfx-hf-ui#156]
Hi, I downloaded the new version 3.1.1 and there are a lot of bugs. 
1. Ma / Ema strategy is not executed via UI. 
2. Strategy editor and back testing not working and is not possible to backtest because it reports an error.
(Basic ema cross from) error "Insufficient trade data."

**Comment by JacobPlaster** [comment]
Hey @drazenbencevic, sorry for the late reply.

I think you may have stumbled across a bug with the data server. When investigating this issue I noticed that if you had updated from an older version of the HF, then the new version would not be able to use the same data directory since there is a slightly new format.

Please try downloading the latest binary here: https://github.com/bitfinexcom/bfx-hf-ui/releases/tag/3.1.1 I've fixed that issue now

When you mention MA not executing via the UI, are you referring to the default strategy or the algo order? Because, with the algo order, it is only supposed to execute once the 2 specified MA's cross over.

**Comment by drazenbencevic** [comment]
Hi, I downloaded the latest version, before that I deleted
everything. Unfortunately,
the problem still exists. The classic MA Crossover does not work, "Failed
to start algo order" also back testing does not work. "insufficient trade
data"

**Comment by JacobPlaster** [comment]
Ok,

What parameters are you using for the backtesting? I can try to reproduce your issue on my end.

Re MA: I'll also try to reproduce that as well

**Comment by drazenbencevic** [comment]
i have tried with all sorts of parameters, one hundred times or more, with
different parameters each time and report the same errors to me each time.
if you want I can make you a video, to see what I'm doing and where the
mistakes are.

**Comment by JacobPlaster** [comment]
Bare with me whilst I debug this, there definitely is an issue but it doesnt seem to affect all machines.

**Comment by drazenbencevic** [comment]
i use windows 10

**Comment by JacobPlaster** [comment]
Hey @drazenbencevic - we released a small version today which includes a bunch of fixes https://github.com/bitfinexcom/bfx-hf-ui/releases/tag/3.1.2

I wasnt able to reproduce you MA algo order issue, but I have fixed the insufficient trade data bug.

**Comment by drazenbencevic** [comment]
Thanks man
